package com.example.paymentsservice.api;

import com.example.paymentsservice.domain.Payment;
import com.example.paymentsservice.domain.PaymentStatus;
import com.example.paymentsservice.exception.InvalidPaymentStateException;
import com.example.paymentsservice.exception.PaymentNotFoundException;
import com.example.paymentsservice.service.PaymentService;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.MockMvc;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.List;

import static org.hamcrest.Matchers.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.when;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

@WebMvcTest(PaymentController.class)
class PaymentControllerTest {

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private ObjectMapper objectMapper;

    @MockBean
    private PaymentService paymentService;

    // -------------------------------------------------------------------------
    // Helper
    // -------------------------------------------------------------------------

    /**
     * Builds a fully-populated Payment with a fixed id and the given status.
     * Uses only public setters so no reflection is required.
     */
    private Payment buildPayment(Long id, PaymentStatus status) {
        Payment p = new Payment() {
            // Payment.id has no public setter (generated by JPA) so we shadow
            // getId() via an anonymous subclass to return the desired value.
            @Override
            public Long getId() { return id; }

            @Override
            public Instant getCreatedAt() { return Instant.parse("2026-04-01T00:00:00Z"); }
        };
        p.setAmount(new BigDecimal("100.00"));
        p.setCurrency("USD");
        p.setDescription("Test payment");
        p.setStatus(status);
        return p;
    }

    // =========================================================================
    // POST /payments
    // =========================================================================

    @Test
    void createPayment_validRequest_returns201WithBody() throws Exception {
        Payment created = buildPayment(1L, PaymentStatus.AUTHORIZED);
        when(paymentService.create(any(Payment.class))).thenReturn(created);

        String body = """
                {
                  "amount": "100.00",
                  "currency": "USD",
                  "description": "Test payment"
                }
                """;

        mockMvc.perform(post("/payments")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(body))
                .andExpect(status().isCreated())
                .andExpect(jsonPath("$.id").value(1))
                .andExpect(jsonPath("$.status").value("AUTHORIZED"));
    }

    @Test
    void createPayment_missingAmount_returns400WithAmountField() throws Exception {
        String body = """
                {
                  "currency": "USD",
                  "description": "Test payment"
                }
                """;

        mockMvc.perform(post("/payments")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(body))
                .andExpect(status().isBadRequest())
                .andExpect(jsonPath("$.amount").exists());
    }

    @Test
    void createPayment_negativeAmount_returns400WithAmountField() throws Exception {
        String body = """
                {
                  "amount": "-1.00",
                  "currency": "USD",
                  "description": "Test payment"
                }
                """;

        mockMvc.perform(post("/payments")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(body))
                .andExpect(status().isBadRequest())
                .andExpect(jsonPath("$.amount").exists());
    }

    @Test
    void createPayment_blankDescription_returns400WithDescriptionField() throws Exception {
        String body = """
                {
                  "amount": "100.00",
                  "currency": "USD",
                  "description": "   "
                }
                """;

        mockMvc.perform(post("/payments")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(body))
                .andExpect(status().isBadRequest())
                .andExpect(jsonPath("$.description").exists());
    }

    @Test
    void createPayment_currencyNotThreeChars_returns400WithCurrencyField() throws Exception {
        String body = """
                {
                  "amount": "100.00",
                  "currency": "US",
                  "description": "Test payment"
                }
                """;

        mockMvc.perform(post("/payments")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(body))
                .andExpect(status().isBadRequest())
                .andExpect(jsonPath("$.currency").exists());
    }

    // =========================================================================
    // GET /payments
    // =========================================================================

    @Test
    void findAll_returns200WithListOfPayments() throws Exception {
        List<Payment> payments = List.of(
                buildPayment(1L, PaymentStatus.AUTHORIZED),
                buildPayment(2L, PaymentStatus.CAPTURED)
        );
        when(paymentService.findAll()).thenReturn(payments);

        mockMvc.perform(get("/payments"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$", hasSize(2)))
                .andExpect(jsonPath("$[0].id").value(1))
                .andExpect(jsonPath("$[1].id").value(2));
    }

    // =========================================================================
    // GET /payments/{id}
    // =========================================================================

    @Test
    void findById_found_returns200WithPaymentBody() throws Exception {
        Payment payment = buildPayment(42L, PaymentStatus.AUTHORIZED);
        when(paymentService.findById(42L)).thenReturn(payment);

        mockMvc.perform(get("/payments/42"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.id").value(42))
                .andExpect(jsonPath("$.status").value("AUTHORIZED"));
    }

    @Test
    void findById_notFound_returns404WithErrorField() throws Exception {
        when(paymentService.findById(99L))
                .thenThrow(new PaymentNotFoundException(99L));

        mockMvc.perform(get("/payments/99"))
                .andExpect(status().isNotFound())
                .andExpect(jsonPath("$.error").exists());
    }

    // =========================================================================
    // POST /payments/{id}/capture
    // =========================================================================

    @Test
    void capture_success_returns200WithCapturedStatus() throws Exception {
        Payment captured = buildPayment(1L, PaymentStatus.CAPTURED);
        when(paymentService.capture(1L)).thenReturn(captured);

        mockMvc.perform(post("/payments/1/capture"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.status").value("CAPTURED"));
    }

    @Test
    void capture_notFound_returns404WithErrorField() throws Exception {
        when(paymentService.capture(99L))
                .thenThrow(new PaymentNotFoundException(99L));

        mockMvc.perform(post("/payments/99/capture"))
                .andExpect(status().isNotFound())
                .andExpect(jsonPath("$.error").exists());
    }

    @Test
    void capture_invalidState_returns409WithErrorField() throws Exception {
        when(paymentService.capture(1L))
                .thenThrow(new InvalidPaymentStateException(
                        "Cannot capture payment 1 in status CAPTURED"));

        mockMvc.perform(post("/payments/1/capture"))
                .andExpect(status().isConflict())
                .andExpect(jsonPath("$.error").exists());
    }

    // =========================================================================
    // POST /payments/{id}/refund
    // =========================================================================

    @Test
    void refund_success_returns200WithRefundedStatus() throws Exception {
        Payment refunded = buildPayment(1L, PaymentStatus.REFUNDED);
        when(paymentService.refund(1L)).thenReturn(refunded);

        mockMvc.perform(post("/payments/1/refund"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.status").value("REFUNDED"));
    }

    @Test
    void refund_notFound_returns404WithErrorField() throws Exception {
        when(paymentService.refund(99L))
                .thenThrow(new PaymentNotFoundException(99L));

        mockMvc.perform(post("/payments/99/refund"))
                .andExpect(status().isNotFound())
                .andExpect(jsonPath("$.error").exists());
    }

    @Test
    void refund_invalidState_returns409WithErrorField() throws Exception {
        when(paymentService.refund(1L))
                .thenThrow(new InvalidPaymentStateException(
                        "Cannot refund payment 1 in status AUTHORIZED"));

        mockMvc.perform(post("/payments/1/refund"))
                .andExpect(status().isConflict())
                .andExpect(jsonPath("$.error").exists());
    }
}
